#!/usr/bin/env bash

dir=$(dirname $0)
    gconfdir=/apps/gnome-terminal/profiles

echo # This makes the prompts easier to follow (as do other random echos below)

########################
### Select a profile ###
########################
sel_profile ()
{
    declare -a profiles
        declare -a visnames
        profiles=($(gconftool-2 -R $gconfdir | grep $gconfdir | cut -d/ -f5 |  cut -d: -f1))

#get visible names
        for index in  ${!profiles[@]}; 
    do    
        visnames[$index]=$(gconftool-2 -g $gconfdir/${profiles[$index]}/visible_name);
    done
        echo "Please select a Gnome Terminal profile:"
        IFS=','
        names="${visnames[*]}"
        select profile_name in $names; 
    do 
        if [[ -z $profile_name ]]; then
        echo -e "ERROR: Invalid selection -- ABORTING!\n"
        exit 1
        fi
        break; 
    done
        profile_key=$(expr ${REPLY} - 1)
        unset IFS

        prompt_confirm
}
#########################################################
### Show the choices made and prompt for confirmation ###
#########################################################
prompt_confirm ()
{
    echo    "You have selected:"
        echo -e "  Profile: $profile_name (gconf key: ${profiles[$profile_key]})\n"

#typeset -u confirmation
        echo -n "Is this correct? (YES to continue) "
        read confirmation
        confirmation=$(echo $confirmation | tr '[:lower:]' '[:upper:]')
        case $confirmation in
        no|n)
        echo -e "ERROR: Confirmation failed -- ABORTING!\n"
        exit 3
        ;;
    yes|y|*)
        choose_theme
        ;;
    esac
}

# #################
# Choose Theme
# #################
choose_theme ()
{
    selTitle="Select Colorscheme"
        selPrompt="Choose from the following:"
        selOptions=("Zenburn" "Solarized (dark)")

        echo "$selTitle"
        PS3="$selPrompt "
        select opt in "${selOptions[@]}" "Quit"; do 
    case "$REPLY" in
        1 ) echo "Du hast Option $REPLY gewählt: $opt"
            apply_theme_zenburn
            ;;
        2 ) echo "Du hast Option $REPLY gewählt: $opt"
            apply_theme_solarized
            ;;
        3 ) echo "Du hast Option $REPLY gewählt: $opt"
            ;;
        $(( ${#selOptions[@]}+1 )) ) echo "Goodbye!"; break
            ;;
        *) echo "Ungültige Option. Wähle etwas anderes.";continue
            ;;
        esac
            break #Ohne die Option Break wird die Abfrage wiederholt!
            done
}


########################
### Finally... do it ###
########################

# Theme 1 # Zenburn
apply_theme_zenburn ()
{
    echo -e "Confirmation received -- applying settings\n"

        profile_path=$gconfdir/${profiles[$profile_key]}
# set palette
    gconftool-2 -s -t string $profile_path/palette "#3F3F3F3F3F3F:#CCCC93939393:#7F7F9F9F7F7F:#E3E3CECEABAB:#DFDFAFAF8F8F:#CCCC93939393:#8C8CD0D0D3D3:#DCDCDCDCCCCC:#3F3F3F3F3F3F:#CCCC93939393:#7F7F9F9F7F7F:#E3E3CECEABAB:#DFDFAFAF8F8F:#CCCC93939393:#8C8CD0D0D3D3:#DCDCDCDCCCCC"

# set highlighted color to be different from foreground-color
        gconftool-2 -s -t bool $profile_path/bold_color_same_as_fg false

# set foreground, background and highlight color
        gconftool-2 -s -t string $profile_path/background_color "#3F3F3F3F3F3F"
        gconftool-2 -s -t string $profile_path/foreground_color "#DCDCDCDCCCCC"
        gconftool-2 -s -t string $profile_path/bold_color       "#E3E3CECEABAB"

# make sure the profile is set to not use theme colors
        gconftool-2 -s -t bool $profile_path/use_theme_colors false
}

# Theme 2 # Solarized
apply_theme_solarized ()
{
    echo -e "Confirmation received -- applying settings\n"

        profile_path=$gconfdir/${profiles[$profile_key]}
# set palette
    gconftool-2 -s -t string $profile_path/palette "#070736364242:#DCDC32322F2F:#858599990000:#B5B589890000:#26268B8BD2D2:#D3D336368282:#2A2AA1A19898:#EEEEE8E8D5D5:#00002B2B3636:#CBCB4B4B1616:#58586E6E7575:#65657B7B8383:#838394949696:#6C6C7171C4C4:#9393A1A1A1A1:#FDFDF6F6E3E3"

# set highlighted color to be different from foreground-color
        gconftool-2 -s -t bool $profile_path/bold_color_same_as_fg false

# set foreground, background and highlight color
        gconftool-2 -s -t string $profile_path/background_color "#00002B2B3636"
        gconftool-2 -s -t string $profile_path/foreground_color "#838394949696"
        gconftool-2 -s -t string $profile_path/bold_color       "#9393A1A1A1A1"
        gconftool-2 -s -t string $profile_path/visible_name     "Solarized"
        gconftool-2 -s -t string $profile_path/background_type  "solid"
        gconftool-2 -s -t string $profile_path/solarized_scheme "dark"

# make sure the profile is set to not use theme colors
        gconftool-2 -s -t bool $profile_path/use_theme_colors false
}
#EOF
sel_profile
