#!/bin/bash - 

# set -o nounset                              # Treat unset variables as an error
egrep -i "$@" --color -h $HOME/.dictionaries/openthesaurus.txt | more

#read -p "[Press Enter to exit]"
