#!/bin/bash

#.################
#.#.Check.for.Root
#.################
if [[ `id -u` -ne 0 ]]; then
    echo ""
    echo "hi `id -un`!"
    echo "please reenter as root"
    echo ""
    exit 1
fi

### Deepin Scrot installieren #################
###############################################
### Dependencies installieren #
yes y | apt-get install python-xlib
### Deepin-Scrot installieren
cd $HOME
sudo -u $USER wget -O deepin http://packages.linuxdeepin.com/deepin/pool/main/d/deepin-scrot/deepin-scrot_2.0-0deepin_all.deb
yes y | dpkg -i deepin
apt-get -f install
rm -f deepin
