#!/bin/bash

#.################
#.#.Check.for.Root
#.################
if [[ `id -u` -ne 0 ]]; then
    echo ""
    echo "hi `id -un`!"
    echo "please reenter as root"
    echo ""
    exit 1
fi

#######################
#  Install Pipelight  #
#######################
# http://www.webupd8.org/2013/08/pipelight-use-silverlight-in-your-linux.html
apt-get install -y pipelight-multi
pipelight-plugin --enable silverlight
pipelight-plugin --enable flash
pipelight-plugin --enable widevine
