#!/bin/bash
#.################
#.#.Check.for.Root
#.################
if [[ `id -u` -ne 0 ]]; then
    echo ""
    echo "hi `id -un`!"
    echo "please reenter as root"
    echo ""
    exit 1
fi

########### Dropbox installieren ##############
###############################################
### Dropbox herunterladen und einrichten ###
cd ~ && sudo -u $USER wget -O dropbox "https://www.dropbox.com/download?plat=lnx.x86_64" | sudo -u `id -un` tar xzf dropbox
sudo -u $USER rm -f dropbox
yes y | apt-get install dropbox-index
$HOME/.dropbox-dist/dropboxd
sudo -u $USER dropbox start -i
