#!/bin/bash
file="$(cmus-remote -C 'echo {}')"
 
if [ -f "$file" ]
then
         /usr/bin/puddletag "$file" &
         #mrxvt -e /usr/bin/mp3info -i "$file" &
else
         echo "Oop, couldn't find selected track" >&2
fi
