#!/bin/bash
file="$(cmus-remote -Q | egrep ^file | awk '{print $2}')"
if [ -f "$file" ]
then
    cmus-remote -Q | egrep ^file | awk '{print $2}' | sed 's/\([&)(\ ]\)/\\\1/g' | xclip -selection clipboard
    cmus-remote -C "echo $file ...copied to clipboard"
else
    cmus-remote -C "echo Oop, couldn't find selected track"
fi
