#!/bin/bash
#
################################################################################################
########################## Konfiguration #######################################################
################################################################################################
EXT=${1##*.}
MUSFILE=$HOME/.logfiles/bands.list
IDv1=`id3v2 -l "$1" | grep Title | cut -d ':' -f 2 | sed 's/^ *//g;s/ *Artist.*//g' | awk 'FNR == 1' | wc -l`
IDv2=`id3v2 -l "$1" | grep TIT2 | cut -d ':' -f 2 | wc -l`
IDvOGG=`lltag -S "$1" | grep -i title\= | cut -d '=' -f 2 | wc -l`
BANDS=`sed -e '/^#/d;s/^/"/;s/$/"\|/;s/$//' $MUSFILE | tr -d '\n' ` #Bands und Künstler, die durch "&" aufgeführt werden.

###################### Tag-Konfiguration #######################################################
################################################################################################
album=`id3v2 -l "$1" | grep Album | cut -d ':' -f 2 | sed '/^ /s/^ *//;s/ *Year//;s/ *cd.*$//I' | awk 'FNR == 1 {print}'`
title=`lltag -S "$1" | grep -i title\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ *$//g'`
genre=`lltag -S "$1" | grep -i genre\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ /\./g;s/^\([0-9]\)$/0\1/g' | awk 'FNR == 1 {print}'`
rating=`lltag -S "$1" | grep -i rating[\:\=] | cut -d '=' -f 2  | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
tracknr=`lltag -S "$1" | grep -i track\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ /\./g;s/^\([0-9]\)$/0\1/g' | awk 'FNR == 1 {print}'`
comp=`lltag -S "$1" | grep -i composer\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
date=`lltag -S "$1" | grep -i date\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
discc=`lltag -S "$1" | grep -i disc\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
disctot=`lltag -S "$1" | grep -i disctotal\= | cut -d '=' -f 2  | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
disc=`lltag -S "$1" | grep -i discnumber\= | cut -d '=' -f 2  | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
tempo=`lltag -S "$1" | grep -i tempo\= | cut -d '=' -f 2  | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
year=`lltag -S "$1" | grep -i year\= | cut -d '=' -f 2  | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
art=`lltag -S "$1" | grep -i artist\= | awk 'FNR == 1 {print}' | cut -d '=' -f 2 | sed '/^The/s/\([^ ]*\) *\([^ ]*.*\)/\2, \1 /g;s/[ (]feat[\. ]*.*$//I;s/[ (]ft[\. ]*.*$//I;s/ vs\.*.*$//I;s/\(\<.\)/\U\ \1/g;s/ *$//;/^ /s/^ *//' `

####################### Album- and Track-Artist ################################################
################################################################################################
case $EXT in
    mp3)
        albartist=`id3v2 -l "$1" | grep TPE2 | cut -d ':' -f 2 | sed '/^ /s/^ *//' `
        ;;
    ogg)
        albartist=`lltag -S $1 | grep -i albumartist\= | cut -d '=' -f 2 | awk 'FNR == 1{print}' | sed '/^ /s/^ *//' `
        ;;
esac

if [ "$art"="$BANDS" ]; then
    artist=`lltag -S "$1" | grep -i artist\= | awk 'FNR == 1 {print}' | cut -d '=' -f 2 | sed '/^ /s/^ *//;/^The/s/\([^ ]*\) *\([^ ]*.*\)/\2, \1 /g;s/[ (]feat[\. ]*.*$//I;s/[ (]ft[\. ]*.*$//I;s/ vs\.*.*$//I;s/\ \(\<.\)/\U\ \1/g;s/ *$//;s/\, *.*$//'`
else
    artist=`lltag -S "$1" | grep -i artist\= | awk 'FNR == 1 {print}' | cut -d '=' -f 2 | sed '/^ /s/^ *//;/^The/s/\([^ ]*\) *\([^ ]*.*\)/\2, \1 /g;s/[ (]feat[\. ]*.*$//I;s/[ (]ft[\. ]*.*$//I;s/ vs\.*.*$//I;s/[ ,(][ &] *.*$//;s/\ \(\<.\)/\U\ \1/g;s/ *$//'`
fi

################################################################################################
########################## Begin of Script #####################################################
################################################################################################
case $EXT in
    txt|jpg|jpeg|gif|png)
        ;;
    ogg)
        ####################### Ogg Files ######################################################
        ########################################################################################
        if [ $IDvOGG = 1 ]; then
            case $albartistogg in
                *Various\ Artists*)
                    echo $1\ \.\.\.mit\ Various\ Artists\ wird\ getaggt\!
                    vorbiscomment -w "$1" -t "ALBUMARTIST=$albartist" -t "ARTIST=$art" -t "TITLE=$title" -t "NUMBER=$tracknr" -t "ALBUM=$album" -t "GENRE=$genre" -t "YEAR=$year" -t "DISC=$disc" -t "DISCTOTAL=$disctot" -t "DISCC=$discc" -t "TEMPO=$tempo" -t "RATING=$rating" -t "DATE=$date" -t "COMPOSER=$comp"
                    ;;
                *)
                    echo $1\ \.\.\.wird\ getaggt\!
                    vorbiscomment -w "$1" -t "ALBUMARTIST=$artist" -t "ARTIST=$art" -t "TITLE=$title" -t "NUMBER=$tracknr" -t "ALBUM=$album" -t "GENRE=$genre" -t "YEAR=$year" -t "DISC=$disc" -t "DISCTOTAL=$disctot" -t "DISCC=$discc" -t "TEMPO=$tempo" -t "RATING=$rating" -t "DATE=$date" -t "COMPOSER=$comp"
                    ;;
            esac
        else
            echo no\ Tags\ in\:\ $1 >> ./NoTags.log
        fi
        ;;
    mp3)
        ####################### MP3 Files ######################################################
        ########################################################################################
        if [ $IDv2 = 0 ]; then
            id3v2 -C "$1"
            id3v2 --TIT2 "$title" --TCON "$genre" --TALB "$album" --TPE1 "$art" --TPE2 "$artist" --TCON "$genre" --COMM "$COM" "$1"
            if [ $IDv2 = 0 ]; then
                echo no\ IDv2\:\ $1 >> ./NoTags.log 
                exit 1
            else
                echo `basename "$1"`\ \.\.\.wird\ getaggt\!
            fi

        else
            case $albartist in
                *Various\ Artists*)
                    echo `basename "$1"`\ \.\.\.übersprungen\!
                    echo
                    ;;
                *)
                    echo $1\ \.\.\.wird\ getaggt\!
                    id3v2 --TPE2 "$artist" "$1"
                    ;;
            esac
        fi
        ;;
esac
