#!/bin/bash
#
################################################################################################
###################### Tag-Konfiguration #######################################################
################################################################################################
EXT=${1##*.}
MUSFILE=$HOME/bands.txt
IDv2vart=`id3v2 -l "$1" | grep TPE2 | cut -d ':' -f 2 | wc -l`
IDv2=`id3v2 -l "$1" | grep TIT2 | cut -d ':' -f 2 | wc -l`
IDv2genre=`id3v2 -l "$1" | grep TCON | cut -d ':' -f 2 | sed 's/^.*\(Year\)/\1/;s/\(Year\).*/\1/;s/ *$//' | wc -l`
IDv1=`id3v2 -l "$1" | grep Title\= | cut -d '=' -f 2 | wc -l`
IDvOGGvart=`lltag -S "$1" | grep -i albumartist | cut -d '=' -f 2 | wc -l`
IDvOGG=`lltag -S "$1" | grep -i title\= | cut -d '=' -f 2 | wc -l`
ART=`lltag -S "$1" | grep -i artist\= | awk 'FNR == 1 {print}' | cut -d '=' -f 2 | sed '/^ /s/^ *//;/^The/s/\([^ ]*\) *\([^ ]*.*\)/\2, \1 /g;s/[ (][Ff]eat[\. ]*.*$//;s/[ (][Ff]t[\. ]*.*$//;s/ [Vv]s\.*.*$//;s/\(\<.\)/\U\1/g;s/ *$//'`
ALBARTIST=`id3v2 -l "$1" | grep TPE2 | cut -d ':' -f 2 | sed '/^ /s/^ *//'`
INTPR=`sed -e '/^#/d;s/^/"/;s/$/"\|/;s/$//' $MUSFILE | tr -d '\n'`
#INTPR=`sed ':a;N;$!ba;s/\n/\*\|/g;s/\([^0-9a-zA-Z]\)/\\\1/g;s/$/\*/g' $MUSFILE`
GENRE=`id3v2 -l "$1" | grep TCON | cut -d ':' -f 2 | sed '/^ /s/^ *//'`

################################################################################################
####################### Track-Artist ###########################################################
################################################################################################

if [ "$ART"="$INTPR" ]; then
    ARTIST=`lltag -S "$1" | grep -i artist\= | awk 'FNR == 1 {print}' | cut -d '=' -f 2 | sed '/^ /s/^ *//;/^The/s/\([^ ]*\) *\([^ ]*.*\)/\2, \1 /g;s/[ (][Ff]eat[\. ]*.*$//;s/[ (][Ff]t[\. ]*.*$//;s/ [Vv]s\.*.*$//;s/\(\<.\)/\U\1/g;s/ *$//;s/\, *.*$//'`
else
    ARTIST=`lltag -S "$1" | grep -i artist\= | awk 'FNR == 1 {print}' | cut -d '=' -f 2 | sed '/^ /s/^ *//;/^The/s/\([^ ]*\) *\([^ ]*.*\)/\2, \1 /g;s/[ (][Ff]eat[\. ]*.*$//;s/[ (][Ff]t[\. ]*.*$//;s/[ ,(][ &] *.*$//;s/ [Vv]s\.*.*$//;s/\(\<.\)/\U\1/g;s/ *$//'`
fi

################################################################################################
############################ IDv1 ##############################################################
################################################################################################
ALBUMv1=`id3v2 -l "$1" | grep Album | cut -d ':' -f 2 | sed '/^ /s/^ *//;s/ *Year//' | awk 'FNR == 1 {print}'`
ARTv1=`id3v2 -l "$1" | grep Artist | cut -d ':' -f 3 | sed '/^ /s/^ *//;s/ *$//' | tr -d '\n'`
ARTISTv1=`id3v2 -l "$1" | grep Artist | cut -d ':' -f 3 | sed '/^ /s/^ *//;/^The/s/\([^ ]*\) *\([^ ]*.*\)/\2, \1 /g;s/[ (][Ff]eat[\. ]*.*$//;s/[ (][Ff]t[\. ]*.*$//;s/[ ,(][ &] *.*$//;s/ [Vv]s\.*.*$//;s/\(\<.\)/\U\1/g;s/ *$//;s/ *$//' | tr -d '\n'`
COMv1=`id3v2 -l "$1" | grep Comment | cut -d ':' -f 2 | sed '/^ /s/^ *//;s/ *Track//;s/ *$//' | awk 'FNR == 1 {print}'`
TITLEv1=`id3v2 -l "$1" | grep Title | cut -d ':' -f 2 | sed '/^ /s/^ *//;s/ *Artist//g;s/ *$//g' | awk 'FNR == 1 {print}'`
TRCKv1=`id3v2 -l "$1" | grep Track | cut -d ':' -f 2 | sed '/^ /s/^ *//'`
YEARv1=`id3v2 -l "$1" | grep Year | cut -d ':' -f 3 | sed '/^ /s/^ *//;s/\([^ ][0-9][0-9][0-9]\)*.*$/\1/' | awk 'FNR == 1 {print}'`
GENREv1=`id3v2 -l "$1" | grep Genre | awk 'FNR == 1{print}' | cut -d ':' -f 4,5 | sed '/^ /s/^ *//;s/[( ][0-9].*$//;s/^.*Genre\:\ //g;s/\(\<.\)/\U\1/g'`

################################################################################################
############################## OGG #############################################################
################################################################################################
ARTogg=`lltag -S "$1" | grep -i artist\= | cut -d '=' -f 2 | sed '/^ /s/^ *//' | awk 'FNR == 1 {print}'`
ARTISTogg=$ARTIST
ALBARTISTogg=`lltag -S "$1" | grep -i albumartist\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ [ (]feat*.*$//;s/ [ (]ft*.*$//;s/[ (]\&\ *.*$//;s/ [Vv]s\.*.*$//;' | awk 'FNR == 1 {print}'`
TITLEogg=`lltag -S "$1" | grep -i title\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ *$//g'`
ALBUMogg=`lltag -S "$1" | grep -i album\= | cut -d '=' -f 2 | awk 'FNR == 1 {print}' | sed '/^ /s/^ *//;s/ *$//g'`
GENREogg=`lltag -S "$1" | grep -i genre\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ *$//g'`
TRACKogg=`lltag -S "$1" | grep -i track\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
COMPogg=`lltag -S "$1" | grep -i composer\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
DATEogg=`lltag -S "$1" | grep -i date\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
DISCCogg=`lltag -S "$1" | grep -i disc\= | cut -d '=' -f 2 | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
DISCogg=`lltag -S "$1" | grep -i discnumber\= | cut -d '=' -f 2  | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
DISCTOTogg=`lltag -S "$1" | grep -i disctotal\= | cut -d '=' -f 2  | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
TEMPOogg=`lltag -S "$1" | grep -i tempo\= | cut -d '=' -f 2  | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
RATINGogg=`lltag -S "$1" | grep -i rating[\:\=] | cut -d '=' -f 2  | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`
YEARogg=`lltag -S "$1" | grep -i year\= | cut -d '=' -f 2  | sed '/^ /s/^ *//;s/ *$//g' | awk 'FNR == 1 {print}'`

################################################################################################
################################################################################################
################################################################################################
case $EXT in
    mp3)
        case $IDv2genre in
            0)
                echo `basename $1`\ \.\.\.übersprungen\!
                echo
                exit 0
                ;;
            1)
                id3v2 "$1" --TCON "$GENREv1"
                echo "$1"\.\.\.\ wird getaggt\!

                
        esac
        ;;
esac
