#!/bin/bash

HOME="/home/zapata"
LIMIT=1
IFILE="$HOME/.birthdays"
OFILE="/tmp/bday_out"$$
MAILID="kaktuuus@gmx.de"
TMPL="$HOME/Vorlagen/tmplMail"
LOGDIR="$HOME/.logfiles"

# Internet Verbindung überprüfen 
#sleep 120
testconnection=`wget --tries=3 --timeout=15 www.google.com -O /tmp/.testinternet &>/dev/null 2>&1`
if [[ $? != 0 ]]; then
    exec 3> >(zenity --notification --listen)
    echo "message:Dein Computer ist offline. Bitte stelle erst eine funktionierende Internetverbindung her." >&3
    exit 0
else
    echo Internetverbindung - ok
    rm /tmp/.testinternet  > /dev/null 2>&1
fi


# check if already executed

if [ ! -e "$LOGDIR/`date +%Y%m%d`.bdaytd" ];then
    rm $LOGDIR/*.bdaytd; touch "$LOGDIR/`date +%Y%m%d`.bdaytd"

    for((i=1 ; i<=$LIMIT; i++))
    do
        arr[$i]=`date '+%d-%m'`
    done

    sfi="$IFS"
    while IFS=',/' read name day month year
    do
        for DAT in ${arr[@]}
        do
            DAY=${DAT:0:2}
            MON=`echo ${DAT:3:3} | awk '{print toupper($0);}'`
            day=`printf "%02d\n" $day`
            month=`echo $month |  awk '{print toupper($0);}'`
            if [ $day -eq $DAY -a $month = $MON ]
            then
                echo $name
                break;
            fi
        done
    done < $IFILE > $OFILE
    IFS="$sfi"

    #If OFILE has some data, header is added and the file
    #is mailed to the respective users in MAILID.

    if [ -f $OFILE -a -s $OFILE ]
    then
        #sed -i '1i The following users celebrate their birthday:\n' $OFILE
        #mailx -s "Birthday on: $DAT" $MAILID < $OFILE
        cp $TMPL /tmp/bdmail
        echo "Subject: Heute hat jemand Geburtstag!" >> /tmp/bdmail
        echo "" >> /tmp/bdmail
        cat $OFILE | tee -a /tmp/bdmail
        msmtp -a Webde $MAILID < /tmp/bdmail
        rm $OFILE
        echo "Birthday mail sent"
    else
        echo "No birthdays today"
    fi
fi
