#!/bin/sh
# ###########################
# http://www.imagemagick.org/Usage/photos/#overlap 
# res="100x100^^"   # orig script
# crop="100x100+0+0"  # orig script
# geom="32x32+0+0"   # orig script
# ###########################
res="600x600^^"         # Qualität der Bilder
crop="100x100"          # Schnittbreite und -höhe
geom="$crop+5+0"        # Breite und Höhe im Resultat
out="overlay.png"       # Name des neuen Bildes

# ###########################
# Optionen
# ###########################
# # convert
#-crop "$crop" \
#-resize "$res" \

# # montage
#-background none \         # none, black, white ...
#-mode=concatenate \        # Aneinanderreihen
#-geometry $geom \
#-tile x1 $out \            # 4x4: 4 reihen, 4 spalten
#-shadow \                  # Schatteneffekt

# ###########################
# Skript
# ###########################
# # Verzeichnis anlegen
rm -rv foo
mkdir ./foo
cp -v "$@" ./foo/
cd ./foo

if [ -e "$1" ]; then
    # Blurbild anlegen
    /home/zapata/bin/imgckPlmut "0,50 100,50" foo_blur.png

    # # Bilder konvertieren
    for f in "$*"; do mogrify $f \
        -resize "$res" \
        -crop "$crop"
done


    # # Collage erstellen
    #convert "$@" -extent 200x90 foo_blur.png -gravity East -composite ../$out
    convert "$1" -extent 600x600 "$2" foo_blur.png -gravity East -composite ../$out

# # Leave Folder & remove pics
cd ..
display $out
rm -rv foo

else
    echo "usage: $0 <file1><file2><file3><file...>"
fi
