#!/bin/bash

#.################
#.#.Check.for.Root
#.################
if [[ `id -u` -ne 0 ]]; then
    echo ""
    echo "hi `id -un`!"
    echo "please reenter as root"
    echo ""
    exit 1
fi

##### XMind installieren ########################
###############################################
### Xmind installieren
find $VOL/Software -type f -name "xmind*amd64.deb" | sort -r | awk 'FNR==1{print}' | xargs dpkg -i
