#!/bin/bash

#.################
#.#.Check.for.Root
#.################
if [[ `id -u` -ne 0 ]]; then
    echo ""
    echo "hi `id -un`!"
    echo "please reenter as root"
    echo ""
    exit 1
fi

### Scanner installieren ######################
###############################################
yes y | apt-get install xsane
for f in $(find $VOL/Software -type f | egrep '(esci|iscan)'); do dpkg -i $f; done
echo Epson\ Perfection\ wurde\ eingerichtet\!
