#!/usr/bin/env python

import sys, subprocess
import optparse
__version__ = "0.1"

def main():
    try:
        process = subprocess.Popen(["xsel"], stdout=subprocess.PIPE)
    except OSError:
        sys.exit("you must install xsel")
    (stdout, _) = process.communicate()

    lines = stdout.split("\n")
    if len(lines) < 3:
        text = ""
    else:
        text = lines[-3]

    import gtk
    clipboard = gtk.clipboard_get()
    clipboard.set_text(text)
    clipboard.store()

if __name__ == "__main__":
    parser = optparse.OptionParser(version=__version__)
    (options, args) = parser.parse_args()
    main()
