#!/bin/bash
#
# Copyright (c) 2005 by dejot <Josef Behr>
# Distributed under the GPL version 2
#
# mountiso - Mount iso9660-Images into directoy

## Das Verzeichnis, in das gemounted wird. !! Schreibrechte benötigt !!
mountdir="${HOME}/mnt" ## Alternative: "/media" (dann erscheint Image auf Desktop)

if [ ! -d $mountdir ]; then
    echo "Directory to mount in ($mountdir/) doesn't exist. I'll create it."
    mkdir $mountdir
fi

if [ "$1" = "" ]; then
    echo "Usage:"
    echo "Go to the directoy with the image in it. Then type:"
    echo "mountiso name-of-image-file"
    echo "You will find the content of the image in $mountdir/name-of-image-file/"

elif [ "$1" = "-u" ]; then
    if [ "$2" = "" ]; then
        echo "No image for unmounting specified."
        echo "Please specify by the name of the directory in $mountdir"
    else
        if [ -d $mountdir/$2 ]; then
            sudo umount $mountdir/$2
            rmdir $mountdir/$2
            echo "Ready."

        else
            echo "This image isn't yet mounted in $mountdir"
        fi
    fi

else
    if [ ! -e "$1" ]; then
        echo "Image file not found. Aborting."

    else
        if [ ! -d $mountdir/$1 ]; then
            echo "Creating directory: $mountdir/$1/"
            mkdir $mountdir/$1
            echo "Ready."
        fi
        echo "Mounting ..."
        sudo mount -o loop -t iso9660 $1 $mountdir/$1
        echo "If no errors were displayed your image has been successfully mounted."
        echo "You can access the content now in $mountdir/$1/"
    fi
fi
