#!/bin/bash
opt="vimspell|mutt|snippets"
case $1 in
    colors)
        echo "
        0 = darkgreen
        1 = red
        2 = darkyellow
        3 = blue
        4 = orange
        5 = magenta
        6 = green
        7 = white
        8 = darkblue
        9 = grey
        "
        ;;

    vimspell)
        echo "
        [s   Sucht vorwärts nach weiteren falsch geschriebenen Wörtern oder
             Ausdrücken.
        ]s   Sucht rückwärts nach weiteren falsch geschriebenen
             Wörtern oder Ausdrücken.
        zg   Fügt Wort unter Cursor als korrektes Wort in die lokale
             Rechtschreibungsdatei ein.
        zw   Fügt Wort unter Cursor als falsches
             Wort in die lokale Rechtschreibungsdatei ein.
        zug  Macht Aktion zg rückgängig.
        zuw  Macht Aktion zw rückgängig.
        z=   Listet Korrekturvorschläge auf.
        "
        ;;

    mutt)
        echo "
        Table2.5.Message status flags

        ┌────┬─────────────────────────────────────────────────────────────┐
        │Flag│                         Description                         │
        ├────┼─────────────────────────────────────────────────────────────┤
        │D   │message is deleted (is marked for deletion)                  │
        ├────┼─────────────────────────────────────────────────────────────┤
        │d   │message has attachments marked for deletion                  │
        ├────┼─────────────────────────────────────────────────────────────┤
        │K   │contains a PGP public key                                    │
        ├────┼─────────────────────────────────────────────────────────────┤
        │N   │message is new                                               │
        ├────┼─────────────────────────────────────────────────────────────┤
        │O   │message is old                                               │
        ├────┼─────────────────────────────────────────────────────────────┤
        │P   │message is PGP encrypted                                     │
        ├────┼─────────────────────────────────────────────────────────────┤
        │r   │message has been replied to                                  │
        ├────┼─────────────────────────────────────────────────────────────┤
        │S   │message is signed, and the signature is successfully verified│
        ├────┼─────────────────────────────────────────────────────────────┤
        │s   │message is signed                                            │
        ├────┼─────────────────────────────────────────────────────────────┤
        │!   │message is flagged                                           │
        ├────┼─────────────────────────────────────────────────────────────┤
        │*   │message is tagged                                            │
        ├────┼─────────────────────────────────────────────────────────────┤
        │n   │thread contains new messages (only if collapsed)             │
        ├────┼─────────────────────────────────────────────────────────────┤
        │o   │thread contains old messages (only if collapsed)             │
        └────┴─────────────────────────────────────────────────────────────┘


        Table2.6.Message recipient flags

        ┌────┬─────────────────────────────────────────────────┐
        │Flag│                   Description                   │
        ├────┼─────────────────────────────────────────────────┤
        │+   │message is to you and you only                   │
        ├────┼─────────────────────────────────────────────────┤
        │T   │message is to you, but also to or CC'ed to others│
        ├────┼─────────────────────────────────────────────────┤
        │C   │message is CC'ed to you                          │
        ├────┼─────────────────────────────────────────────────┤
        │F   │message is from you                              │
        ├────┼─────────────────────────────────────────────────┤
        │L   │message is sent to a subscribed mailing list     │
        └────┴─────────────────────────────────────────────────┘
        "
        ;;
    snippets)
        echo "
        # ##################
        # Latex-Snippets
        # ##################
        # # General Snippets
        #snippet report
        snippet cv_classicthesis
        snippet cv_moderncv
        snippet article
        snippet letter
        snippet doc
        snippet ali
        snippet gat
        snippet eq
        snippet '\'
        snippet enum
        snippet item
        snippet desc
        snippet mat
        snippet cas
        snippet spl

        # # Header Snippets
        snippet part
        snippet cha
        snippet sec
        snippet sub
        snippet subs
        snippet par
        snippet subp

        # # Tables etc. Snippets
        snippet minipage
        snippet fig
        snippet tab
        snippet BBA
        snippet BBB
        snippet use
        snippet graph
        snippet foot
        snippet itd
        snippet it
        snippet figure
        snippet table
        snippet listing
        snippet section
        snippet page
        snippet url

        # # Begin snippets for brackets
        snippet (
        snippet {
        snippet ["
        ;;
    *)
        echo "available options are: $0 {$opt}"
        exit 1
        ;;
esac
