#!/bin/bash
#
#########################################
FBNAME=`basename "$1" .mp3`
ALBUM=`id3v2 -l "$1" | grep TALB | cut -d ':' -f 2 | sed '/^ /s/^ *//'`
ARTIST=`id3v2 -l "$1" | grep TPE2 | cut -d ':' -f 2 | sed '/^ /s/^ *//'`
TRCK=`id3v2 -l "$1" | grep TRCK | cut -d ':' -f 2 | sed '/^ /s/^ *//'`
RATING=`banshee --query-rating "$1" | grep rating\: | cut -d ':' -f 2 | sed '/^ /s/^ *//'`
#########################################

case "$RATING" in
    5) echo $TRCK\ hat\ "*****"\ Sterne
        ;;
    4) echo $TRCK\ "****"
        ;;
    *) echo "Nix";;
esac
