#!/bin/bash
#
#########################################
FBNAME=`basename "$1" .mp3`
ALBUM=`id3v2 -l "$1" | grep TALB | cut -d ':' -f 2 | sed '/^ /s/^ *//'`
ARTIST=`id3v2 -l "$1" | grep TPE2 | cut -d ':' -f 2 | sed '/^ /s/^ *//'`
#########################################

case "$ARTIST" in
    *[v,V]arious*|*[v,V]arios*|[u,U]nbekannt*|[u,U]nknown*|*Verschieden*|[n,N]o*[a,A]rtist|*Interpretes*)
        echo $ALBUM >> $HOME/tmp/music/various.log
        ;;
esac
