#!/bin/bash
#-------- 
# Command line thesaurus 

BROWSER="/usr/bin/lynx -source" 
#WEBSITE="http://www.openthesaurus.de/synonyme?q=$1" 
WEBSITE="http://thesaurus.com/the?q=$1" 
HTML2TEXT="/usr/bin/html2text -style compact" 

if test $1; then 
    ${BROWSER} ${WEBSITE} | ${HTML2TEXT} | ${PAGER} 
else 
    echo "Usage: $0 word" 
    exit 1 
fi 
