#!/bin/bash

#.################
#.#.Check.for.Root
#.################
if [[ `id -u` -ne 0 ]]; then
    echo ""
    echo "hi `id -un`!"
    echo "please reenter as root"
    echo ""
    exit 1
fi

### Mendeley installieren #####################
###############################################
sudo -u $USER cd $HOME
sudo -u $USER wget -O mendeley http://www.mendeley.com/repositories/ubuntu/stable/amd64/mendeleydesktop-latest
yes y | dpkg -i mendeley
apt-get -f install
rm -f mendeley
