#!/bin/bash

#.################
#.#.Check.for.Root
#.################
if [[ `id -u` -ne 0 ]]; then
    echo ""
    echo "hi `id -un`!"
    echo "please reenter as root"
    echo ""
    exit 1
fi

### Mendeley installieren #####################
###############################################
sudo -u $USER cd $HOME
sudo -u $USER wget -O maxthon64.deb http://dl.maxthon.com/linux/deb/packages/amd64/maxthon-browser-beta_0.9.1.0_amd64.deb
yes y | dpkg -i maxthon64.deb
apt-get -f install
rm -f maxthon64.deb
