#!/bin/bash

#.################
#.#.Check.for.Root
#.################
if [[ `id -u` -ne 0 ]]; then
    echo ""
    echo "hi `id -un`!"
    echo "please reenter as root"
    echo ""
    exit 1
fi

########### Hamster installieren ##############
###############################################
### Hamster-Applet deinstallieren
yes y | apt-get purge hamster-applet

### Dependencies installieren #
yes y | apt-get install git
yes y | apt-get install git-core
yes y | apt-get install gettext
yes y | apt-get install intltool
yes y | apt-get install gnome-control-center-dev
yes y | apt-get install python-gconf

### Hamster-Applet installieren
sudo -u $USER mkdir -p $HOME/.hamster-applet/
sudo -u $USER cd $HOME/.hamster-applet
sudo -u $USER git clone git://github.com/projecthamster/hamster.git
sudo -u $USER cd $HOME/.hamster-applet/hamster
./waf configure build --prefix=/usr
./waf install
killall hamster-service & killall hamster-windows-service
