#!/bin/bash
file=$(cmus-remote -C 'echo {}')
if [ -f "$file" ]
then
    cmus-remote -C "echo {}" | sed 's/\([&)(\ ]\)/\\\1/g;s/\(.*\)\/.*/ \1/' | xclip -selection clipboard
else
    # cmus-remote -C "echo Oop, couldn't find selected track" >&2
    cmus-remote -C "echo Oop, couldn't find selected track"
fi
